# Generated by Django 5.2 on 2025-04-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_name', models.CharField(max_length=255, unique=True)),
                ('is_lock', models.BooleanField(default=False)),
                ('locked_by_pid', models.IntegerField(blank=True, null=True)),
                ('lock_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lock_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
