# Generated by Django 4.2.20 on 2025-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='lock_status',
            new_name='is_lock',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='created_at',
            new_name='lock_at',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='updated_at',
            new_name='lock_updated_at',
        ),
        migrations.AddField(
            model_name='lock',
            name='locked_by_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
