# Generated by Django 4.2.20 on 2025-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_log', '0002_rename_lock_status_lock_is_lock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
