# Generated by Django 5.2 on 2025-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='u_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
